### ISSUE TITLE
关于仓库中数据集链接失效的问题

### ISSUE THREAD

**Issue by Y-M-Y** [txyugood/paddlex_steel_defect_seg#1]
你好，请问你在文档中提到的6666张转换为分割的数据集是在哪里下载呢？我自己转换失败了，非常感谢你的指导！

**Comment by txyugood** [comment]
应该是这个，https://aistudio.baidu.com/aistudio/datasetdetail/108486

**Comment by Y-M-Y** [comment]
> 应该是这个，https://aistudio.baidu.com/aistudio/datasetdetail/108486

好的！谢谢！可以方便问下您是用什么工具转换的吗？我之前用的是[这个](https://github.com/PaddlePaddle/awesome-DeepLearning/blob/master/Paddle_Industry_Practice_Sample_Library/paddlex_steel_defect_seg-master/code/prepare_dataset.py)，但是这个工具对缺陷和类别没有设置明显的颜色差异，肉眼难以分辨。
我也正在学习中，如果有问的比较菜鸟的地方，还请见谅！

**Comment by txyugood** [comment]
https://github.com/txyugood/paddlex_steel_defect_seg/blob/master/prepare_dataset.py这个

**Comment by Y-M-Y** [comment]
> [https://github.com/txyugood/paddlex_steel_defect_seg/blob/master/prepare_dataset.py这个](https://github.com/txyugood/paddlex_steel_defect_seg/blob/master/prepare_dataset.py%E8%BF%99%E4%B8%AA)

好的，谢谢！已经在学习了
